### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by jessgoldq4** [dvdvdmt/popup-tab-switcher#61]
Simply put, the settings aren't saved once I close the settings popup window

**Comment by dvdvdmt** [comment]
Thanks for reporting this! I see the problem

**Comment by dvdvdmt** [comment]
This should be fixed in v2022.2 when this version will be published in chrome web store. You can also help me and check that it works for you. Simply install the version using the archive file that is attached to the latest release https://github.com/dvdvdmt/popup-tab-switcher/releases/tag/v2022.2
Here is the video:

https://user-images.githubusercontent.com/8076700/187972627-fa256c47-7ff1-4037-b3ce-338e780cf51e.mov
